title: Typing-Effect
description: Typing-Effect is a UI Component for React which provides elegant typing effects with very few lines of code
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
